### ISSUE TITLE
Undefined method first for nil:NilClass when using Rack::Locale on Safari ("HTTP_ACCEPT_LANGUAGE"=>"en-us")

### ISSUE THREAD

**Issue by jmettraux** [rack/rack-contrib#135]
As detailed in https://github.com/jmettraux/rack_contrib_locale_issue

Previously "reported" in https://github.com/rack/rack-contrib/pull/133

for short:

```ruby
require 'i18n'
require 'rack'
require 'rack/contrib'

I18n.load_path = Dir['*.yml']
I18n.backend.load_translations

use Rack::Locale

class App

  def self.call(env)

#require 'pp'; pp env
    [ 200, {}, [ 'ok' ] ]
  end
end

run App
```
with:
```
GEM
  remote: https://rubygems.org/
  specs:
    i18n (0.8.6)
    rack (1.6.8)
    rack-contrib (1.5.0)
      rack (~> 1.4)
```
resulting with Safari (HTTP_ACCEPT_LANGUAGE: "en-us") in:
```
NoMethodError: undefined method `first' for nil:NilClass
	/Users/jmettraux/.gem/ruby/2.3.4/gems/rack-contrib-1.5.0/lib/rack/contrib/locale.rb:43:in `accept_locale'
	/Users/jmettraux/.gem/ruby/2.3.4/gems/rack-contrib-1.5.0/lib/rack/contrib/locale.rb:13:in `call'
	/Users/jmettraux/.gem/ruby/2.3.4/gems/rack-1.6.8/lib/rack/tempfile_reaper.rb:15:in `call'
	/Users/jmettraux/.gem/ruby/2.3.4/gems/rack-1.6.8/lib/rack/lint.rb:49:in `_call'
	/Users/jmettraux/.gem/ruby/2.3.4/gems/rack-1.6.8/lib/rack/lint.rb:37:in `call'
	/Users/jmettraux/.gem/ruby/2.3.4/gems/rack-1.6.8/lib/rack/showexceptions.rb:24:in `call'
	/Users/jmettraux/.gem/ruby/2.3.4/gems/rack-1.6.8/lib/rack/commonlogger.rb:33:in `call'
	/Users/jmettraux/.gem/ruby/2.3.4/gems/rack-1.6.8/lib/rack/chunked.rb:54:in `call'
	/Users/jmettraux/.gem/ruby/2.3.4/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
	/Users/jmettraux/.gem/ruby/2.3.4/gems/rack-1.6.8/lib/rack/handler/webrick.rb:88:in `service'
	/Users/jmettraux/.rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/Users/jmettraux/.rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/Users/jmettraux/.rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
::1 - - [29/Aug/2017:10:57:33 +0900] "GET / HTTP/1.1" 500 45101 0.0108
```

**Comment by mpalmer** [comment]
Fixed by #138.
